use super::{Bridge, Interface, Network};
use crate::resource::native::NativeDirective;
use anyhow::Result;
use std::collections::BTreeSet;

#[derive(Debug, Clone)]
pub(crate) struct ParsedNetwork {
    pub(crate) managed: Network,
    pub(crate) unmodeled: Vec<NativeDirective>,
}

pub(crate) fn parse(content: &str, current: &Network) -> Result<ParsedNetwork> {
    #[derive(Default)]
    struct Stanza {
        line: usize,
        definition: String,
        name: String,
        family: String,
        method: String,
        address: Option<String>,
        gateway: Option<String>,
        ports: Option<Vec<String>>,
        stp: Option<bool>,
        forward_delay: Option<u16>,
    }

    fn generated_comment(line: &str) -> bool {
        matches!(
            line,
            "#" | "# network interface settings; autogenerated"
                | "# Please do NOT modify this file directly, unless you know what"
                | "# you're doing."
                | "# If you want to manage parts of the network configuration manually,"
                | "# please utilize the 'source' or 'source-directory' directives to do"
                | "# so."
                | "# PVE will preserve these directives, but will NOT read its network"
                | "# configuration from sourced files, so do not attempt to move any of"
                | "# the PVE managed interfaces into external files!"
                | "# Managed by PVE State"
        )
    }

    let mut interfaces = Vec::new();
    let mut bridges = Vec::new();
    let mut stanzas = Vec::new();
    let mut automatic = Vec::new();
    let mut unmodeled = Vec::new();
    let mut stanza: Option<Stanza> = None;
    for (index, raw) in content.lines().enumerate() {
        let line_number = index + 1;
        let line = raw.trim();
        if line.is_empty() || generated_comment(line) {
            continue;
        }
        if line.starts_with('#') {
            unmodeled.push(NativeDirective::new(
                line_number,
                line,
                "custom comments are not represented by the local network model",
            ));
            continue;
        }
        if let Some(definition) = line.strip_prefix("iface ") {
            if let Some(previous) = stanza.take() {
                stanzas.push(previous);
            }
            let parts = definition.split_whitespace().collect::<Vec<_>>();
            if parts.len() == 3 {
                stanza = Some(Stanza {
                    line: line_number,
                    definition: line.to_string(),
                    name: parts[0].into(),
                    family: parts[1].into(),
                    method: parts[2].into(),
                    ..Stanza::default()
                });
            } else {
                unmodeled.push(NativeDirective::new(
                    line_number,
                    line,
                    "malformed interface definition",
                ));
            }
            continue;
        }
        if let Some(names) = line.strip_prefix("auto ") {
            if let Some(previous) = stanza.take() {
                stanzas.push(previous);
            }
            automatic.extend(
                names
                    .split_whitespace()
                    .map(|name| (line_number, name.to_string())),
            );
            continue;
        }
        if line == "source /etc/network/interfaces.d/*" {
            if let Some(previous) = stanza.take() {
                stanzas.push(previous);
            }
            continue;
        }
        let Some(active) = stanza.as_mut() else {
            unmodeled.push(NativeDirective::new(
                line_number,
                line,
                "unsupported top-level network directive",
            ));
            continue;
        };
        let Some((key, value)) = line.split_once(char::is_whitespace) else {
            unmodeled.push(NativeDirective::new(
                line_number,
                line,
                "malformed interface directive",
            ));
            continue;
        };
        let value = value.trim();
        match key {
            "address" if active.address.is_none() => active.address = Some(value.into()),
            "address" => unmodeled.push(NativeDirective::new(
                line_number,
                line,
                "multiple addresses in one stanza are not supported",
            )),
            "gateway" if active.gateway.is_none() => active.gateway = Some(value.into()),
            "gateway" => unmodeled.push(NativeDirective::new(
                line_number,
                line,
                "multiple gateways in one stanza are not supported",
            )),
            "bridge-ports" => {
                if active.ports.is_some() {
                    unmodeled.push(NativeDirective::new(
                        line_number,
                        line,
                        "duplicate bridge-ports directive",
                    ));
                } else {
                    active.ports = Some(if value == "none" {
                        Vec::new()
                    } else {
                        value.split_whitespace().map(str::to_string).collect()
                    });
                }
            },
            "bridge-stp" if active.stp.is_some() => unmodeled.push(NativeDirective::new(
                line_number,
                line,
                "duplicate bridge-stp directive",
            )),
            "bridge-stp" => match value {
                "on" | "yes" | "1" => active.stp = Some(true),
                "off" | "no" | "0" => active.stp = Some(false),
                _ => unmodeled.push(NativeDirective::new(
                    line_number,
                    line,
                    "bridge-stp is not a supported boolean",
                )),
            },
            "bridge-fd" if active.forward_delay.is_some() => {
                unmodeled.push(NativeDirective::new(
                    line_number,
                    line,
                    "duplicate bridge-fd directive",
                ));
            },
            "bridge-fd" => match value.parse() {
                Ok(value) => active.forward_delay = Some(value),
                Err(_) => unmodeled.push(NativeDirective::new(
                    line_number,
                    line,
                    "bridge-fd is not a valid integer",
                )),
            },
            _ => unmodeled.push(NativeDirective::new(
                line_number,
                line,
                format!("unsupported interface directive `{key}`"),
            )),
        }
    }
    if let Some(previous) = stanza {
        stanzas.push(previous);
    }

    let mut defined = BTreeSet::new();
    for stanza in &stanzas {
        if !defined.insert((stanza.name.clone(), stanza.family.clone())) {
            unmodeled.push(NativeDirective::new(
                stanza.line,
                &stanza.definition,
                "multiple stanzas for the same interface and address family",
            ));
        }
    }
    let mut processed_inet = BTreeSet::new();
    for stanza in stanzas.iter().filter(|stanza| stanza.family == "inet") {
        if !processed_inet.insert(stanza.name.clone()) {
            continue;
        }
        if stanza.name == "lo" && stanza.method == "loopback" {
            continue;
        }
        if let Some(ports) = &stanza.ports {
            let Ok(method) = stanza.method.parse() else {
                unmodeled.push(NativeDirective::new(
                    stanza.line,
                    &stanza.definition,
                    format!("unsupported IPv4 address method `{}`", stanza.method),
                ));
                continue;
            };
            bridges.push(Bridge {
                name: stanza.name.clone(),
                method,
                address: stanza.address.clone(),
                gateway: stanza.gateway.clone(),
                ipv6: None,
                gateway6: None,
                ports: ports.clone(),
                stp: stanza.stp.unwrap_or(false),
                forward_delay: stanza.forward_delay.unwrap_or_default(),
            });
        } else if stanza.address.is_none()
            && stanza.gateway.is_none()
            && stanza.stp.is_none()
            && stanza.forward_delay.is_none()
        {
            let Ok(method) = stanza.method.parse() else {
                unmodeled.push(NativeDirective::new(
                    stanza.line,
                    &stanza.definition,
                    format!("unsupported IPv4 address method `{}`", stanza.method),
                ));
                continue;
            };
            interfaces.push(Interface {
                name: stanza.name.clone(),
                method,
            });
        } else {
            unmodeled.push(NativeDirective::new(
                stanza.line,
                &stanza.definition,
                "addressed non-bridge interfaces are not represented by the local model",
            ));
        }
    }
    let mut processed_inet6 = BTreeSet::new();
    for stanza in stanzas.iter().filter(|stanza| stanza.family == "inet6") {
        if !processed_inet6.insert(stanza.name.clone()) {
            continue;
        }
        if stanza.method != "static" {
            unmodeled.push(NativeDirective::new(
                stanza.line,
                &stanza.definition,
                "only static IPv6 bridge stanzas are supported",
            ));
            continue;
        }
        let Some(bridge) = bridges.iter_mut().find(|bridge| bridge.name == stanza.name) else {
            unmodeled.push(NativeDirective::new(
                stanza.line,
                &stanza.definition,
                "IPv6 configuration is only modeled for bridges",
            ));
            continue;
        };
        bridge.ipv6 = stanza.address.clone();
        bridge.gateway6 = stanza.gateway.clone();
    }
    for stanza in stanzas
        .iter()
        .filter(|stanza| stanza.family != "inet" && stanza.family != "inet6")
    {
        unmodeled.push(NativeDirective::new(
            stanza.line,
            &stanza.definition,
            format!("unsupported address family `{}`", stanza.family),
        ));
    }

    let reproducible_auto = bridges
        .iter()
        .map(|bridge| bridge.name.as_str())
        .chain(std::iter::once("lo"))
        .collect::<BTreeSet<_>>();
    for (line, name) in automatic {
        if !reproducible_auto.contains(name.as_str()) {
            unmodeled.push(NativeDirective::new(
                line,
                &format!("auto {name}"),
                "automatic activation for this interface is not represented by the local model",
            ));
        }
    }

    let mut adopted = current.clone();
    adopted.interfaces = interfaces;
    adopted.bridges = bridges;
    Ok(ParsedNetwork {
        managed: adopted,
        unmodeled,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn local() -> Network {
        serde_yaml::from_str(include_str!("../../../examples/basic/config/network.yml")).unwrap()
    }

    #[test]
    fn parse_render_parse_is_stable_with_crlf_input() {
        let current = local();
        let rendered = super::super::render::render(&current).replace('\n', "\r\n");
        let first = parse(&rendered, &current).unwrap();
        assert!(first.unmodeled.is_empty());
        let rerendered = super::super::render::render(&first.managed);
        let second = parse(&rerendered, &first.managed).unwrap();
        assert!(second.unmodeled.is_empty());
        assert_eq!(
            serde_json::to_value(first.managed).unwrap(),
            serde_json::to_value(second.managed).unwrap()
        );
    }

    #[test]
    fn supported_ipv4_and_ipv6_bridge_is_parsed() {
        let captured = "iface eno1 inet manual\n\nauto vmbr0\niface vmbr0 inet static\n address 192.0.2.10/24\n gateway 192.0.2.1\n bridge-ports eno1\n bridge-stp off\n bridge-fd 0\n\niface vmbr0 inet6 static\n address 2001:db8::10/64\n gateway 2001:db8::1\n";
        let parsed = parse(captured, &local()).unwrap();
        assert!(parsed.unmodeled.is_empty());
        assert_eq!(parsed.managed.interfaces[0].name, "eno1");
        assert_eq!(
            parsed.managed.bridges[0].ipv6.as_deref(),
            Some("2001:db8::10/64")
        );
    }

    #[test]
    fn mixed_supported_and_unsupported_syntax_is_retained_as_blockers() {
        let captured = "iface vmbr0 inet static\n address 192.0.2.10/24\n bridge-ports eno1\n mtu 9000\n post-up /usr/local/bin/finish\n";
        let parsed = parse(captured, &local()).unwrap();
        assert_eq!(
            parsed.managed.bridges[0].address.as_deref(),
            Some("192.0.2.10/24")
        );
        let diagnostics = parsed
            .unmodeled
            .iter()
            .map(NativeDirective::diagnostic)
            .collect::<Vec<_>>()
            .join("\n");
        assert!(diagnostics.contains("mtu"));
        assert!(diagnostics.contains("post-up"));
    }

    #[test]
    fn multiple_addresses_and_custom_top_level_syntax_are_reported() {
        let captured = "# keep this operator note\nallow-hotplug eno1\niface vmbr0 inet static\n address 192.0.2.10/24\n address 192.0.2.11/24\n bridge-ports eno1\n";
        let parsed = parse(captured, &local()).unwrap();
        let diagnostics = parsed
            .unmodeled
            .iter()
            .map(NativeDirective::diagnostic)
            .collect::<Vec<_>>()
            .join("\n");
        assert!(diagnostics.contains("custom comments"));
        assert!(diagnostics.contains("unsupported top-level"));
        assert!(diagnostics.contains("multiple addresses"));
    }

    #[test]
    fn bare_dhcp_is_supported_but_dhcp_options_are_not() {
        let parsed = parse("iface eno1 inet dhcp\n", &local()).unwrap();
        assert!(parsed.unmodeled.is_empty());
        assert_eq!(parsed.managed.interfaces[0].method, "dhcp");
        let with_option = parse("iface eno1 inet dhcp\n metric 100\n", &local()).unwrap();
        assert_eq!(with_option.unmodeled[0].text, "metric 100");
    }
}
